### ISSUE TITLE
Cannot find module 'core-js/modules/es6.array.filter'

### ISSUE THREAD

**Issue by Cigoler** [nareshbhatia/gatsby-starter-material-ui#1]
Fresh build I'm getting this error trying to run gatsby develop.

**Comment by nareshbhatia** [comment]
Hmmm... I just did a fresh install from GitHub and it ran without any issues. Did you run yarn or npm?

```
$ yarn
$ gatsby develop
```

**Comment by Cigoler** [comment]
npm install,

I guess it's to do with NPM as when I look in that particular core-js directory the es6.array.filter file is not present but a bunch of others are. It's my first look at Gatsby/react so I don't know if I'm doing anything obviously wrong. Just following the guide on the web.

Typing 'yarn' just results in an error saying there are no scenarios.

**Comment by nareshbhatia** [comment]
Yep, it's definitely something to do with npm :-).

npm and yarn are two different package managers that do the same thing. I prefer yarn a bit more (see my reasoning [here](https://medium.com/@NareshBhatia/sharing-ui-components-with-lerna-and-yarn-workspaces-be1ebca06efe)). You will notice that the repo has a file called `yarn.lock`, which locks the exact versions of all the dependencies. npm has a similar concept with `package-lock.json`. Since you are using npm, you are getting dependencies that are inconsistent with the yarn.lock file.

My suggestion is to install [yarn](https://yarnpkg.com) and run the build again. It should work just fine. Let me know how it goes!
