### ISSUE TITLE
Dev Build Instructions Do Not Work

### ISSUE THREAD

**Issue by DanielDwyer** [nareshbhatia/gatsby-starter-material-ui#2]
It appears that after you run ```$ yarn``` you must still run ```$ npm i``` or this error will throw: ```error There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.```

And then after running ```$ npm i``` this error throws when trying to run the ```$ gatsby develop``` command: ```error UNHANDLED REJECTION Error: Cannot find module 'core-js/modules/es6.array.filter'```

Your base looks like it would be fun to work with if I could get it running. Thanks!

**Comment by nareshbhatia** [comment]
Hmmm, have you installed gatsby-cli? (see prerequisite in README.md).

Once gatsby-cli is installed, there should be no need to run npm. I am using only yarn. That's why I have a `yarn.lock` file in the repo.

(Note that there is no `package-lock.json` file in the repo. If you find one in your local directory, that means you have accidentally run `npm i`.)

Let me know how it goes.

**Comment by DanielDwyer** [comment]
I got it working. It was certainly a user error 👍 Thanks for the base!

**Comment by nareshbhatia** [comment]
FYI, I just pushed some minor restructuring of the code to make production builds more robust. Essentially the `withRoot()` calls have now been pulled up to the page level. Also minor changes in other files. Please use the updated template.

**Comment by nareshbhatia** [comment]
Ah, one more thing - README file has been updated with better instructions. I recommend not to use `gatsby` from the command line because that will invoke the global gatsby command. Always use the yarn commands specified in the README file. These invoke local gatsby commands, thus more compatible with what the template expects.
